export const CALCULATOR_ACTIONS = {
  UPDATE_DISPLAY: 'UPDATE_DISPLAY',
  CLEAR_DISPLAY: 'CLEAR_DISPLAY',
  CLEAR_LAST_NUMBER: 'CLEAR_LAST_NUMBER',
  OPERATOR: 'OPERATOR',
  SECOND_VALUE: 'SECOND_VALUE',
  CALCULATE_RESULT: 'CALCULATE_RESULT',
  UPDATE_PREV: 'UPDATE_PREV',
  DELETE_PREV: 'DELETE_PREV',
  CHANGE_SIGN: 'CHANGE_SIGN',
  CLEAR_HISTORY: 'CLEAR_HISTORY',
  GET_LOCAL_STORE: ' GET_LOCAL_STORE',
}
